2025-03-26 13:24:35 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\character.routes.js:46:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 13:25:42 error: uncaughtException: app.use() requires a middleware function
TypeError: app.use() requires a middleware function
    at Function.use (C:\wamp64\www\UmbraEternum\node_modules\express\lib\application.js:217:11)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\index.js:39:5)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49
2025-03-26 13:26:12 error: uncaughtException: app.use() requires a middleware function
TypeError: app.use() requires a middleware function
    at Function.use (C:\wamp64\www\UmbraEternum\node_modules\express\lib\application.js:217:11)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\index.js:40:5)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49
2025-03-26 13:26:22 error: uncaughtException: app.use() requires a middleware function
TypeError: app.use() requires a middleware function
    at Function.use (C:\wamp64\www\UmbraEternum\node_modules\express\lib\application.js:217:11)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\index.js:40:5)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49
2025-03-26 13:31:34 error: uncaughtException: app.use() requires a middleware function
TypeError: app.use() requires a middleware function
    at Function.use (C:\wamp64\www\UmbraEternum\node_modules\express\lib\application.js:217:11)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\index.js:51:5)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49
2025-03-26 13:31:38 error: uncaughtException: app.use() requires a middleware function
TypeError: app.use() requires a middleware function
    at Function.use (C:\wamp64\www\UmbraEternum\node_modules\express\lib\application.js:217:11)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\index.js:51:5)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49
2025-03-26 13:36:17 error: uncaughtException: app.use() requires a middleware function
TypeError: app.use() requires a middleware function
    at Function.use (C:\wamp64\www\UmbraEternum\node_modules\express\lib\application.js:217:11)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\index.js:51:5)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49
2025-03-26 13:53:50 error: uncaughtException: app.use() requires a middleware function
TypeError: app.use() requires a middleware function
    at Function.use (C:\wamp64\www\UmbraEternum\node_modules\express\lib\application.js:217:11)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\index.js:51:5)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49
2025-03-26 15:33:50 error: uncaughtException: app.use() requires a middleware function
TypeError: app.use() requires a middleware function
    at Function.use (C:\wamp64\www\UmbraEternum\node_modules\express\lib\application.js:217:11)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\index.js:51:5)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49
2025-03-26 15:37:42 error: uncaughtException: Cannot find module '../models/RefreshToken'
Require stack:
- C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js
- C:\wamp64\www\UmbraEternum\src\index.js
Error: Cannot find module '../models/RefreshToken'
Require stack:
- C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js
- C:\wamp64\www\UmbraEternum\src\index.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function._load (node:internal/modules/cjs/loader:1055:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:7:27)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
2025-03-26 15:37:57 error: uncaughtException: Cannot find module '../models/RefreshToken'
Require stack:
- C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js
- C:\wamp64\www\UmbraEternum\src\index.js
Error: Cannot find module '../models/RefreshToken'
Require stack:
- C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js
- C:\wamp64\www\UmbraEternum\src\index.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function._load (node:internal/modules/cjs/loader:1055:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:7:27)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
2025-03-26 15:38:26 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:38:28 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:38:48 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:39:04 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:39:12 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:46:14 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:46:14 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:46:34 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:46:34 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:46:51 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:46:51 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:46:54 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:46:54 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:47:03 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:47:03 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:47:06 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:47:06 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:47:17 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:47:17 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:47:19 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:47:19 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:47:28 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:47:28 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:47:48 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:47:48 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:48:01 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:48:01 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:48:14 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:48:14 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:49:14 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-26 15:49:14 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:87:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-27 09:17:50 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:160:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-27 09:19:02 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\routes\auth.routes.js:160:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
2025-03-27 15:16:54 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\index-for-now.js:296:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49
2025-03-27 15:17:09 error: uncaughtException: next is not a function
TypeError: next is not a function
    at validate (C:\wamp64\www\UmbraEternum\src\middlewares\validation.middleware.js:25:3)
    at Object.<anonymous> (C:\wamp64\www\UmbraEternum\src\index-for-now.js:296:3)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49
2025-03-27 15:17:50 error: uncaughtException: listen EADDRINUSE: address already in use :::34567
Error: listen EADDRINUSE: address already in use :::34567
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at startServer (C:\wamp64\www\UmbraEternum\src\index-for-now.js:1328:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
